services:
  postgres:
    image: postgres:14-alpine
    container_name: household_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: household
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: ./docker
    container_name: household_app
    restart: unless-stopped
    user: superset
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/household
      - PYTHONPATH=/workspace/src
      - SUPERSET_SECRET_KEY=${SUPERSET_SECRET_KEY}
    ports:
      - "8088:8088"
    depends_on:
      - postgres
    volumes:
      - .:/workspace
      - ./data:/workspace/data
      - ./src:/workspace/src
    working_dir: /workspace